- www/html/auth_login.html
- www/html/simpleid.css
> Fix missing $security_message in auth_login.html

- www/core/Auth/AuthManager.php
- www/core/Auth/AuthModule.php
- www/core/Auth/LoginFormSubmitEvent.php
- www/core/Auth/OTPAuthSchemeModule.php
> Fixes OTP setup and verification

- .github/workflows/ci.yml
- composer.json
- www/core/Models/User.php
- www/core/Protocols/HTTPResponse.php
- www/core/Protocols/OpenID/Response.php
- www/core/Util/ArrayWrapper.php
* Fixes new method signature requirements in `ArrayAccess` from PHP 8.1
* Also pulled FatFree 3.8 to fix #54.
> Fix PHP 8.1 compatibility

- www/config.php.dist
> Change default logging level

- composer.json
- www/bootstrap.inc.php
- www/core/Protocols/Connect/ConnectModule.php
- www/core/Protocols/OAuth/OAuthModule.php
- www/core/Protocols/OAuth/Token.php
- www/core/Util/OpaqueIdentifier.php
- www/core/Util/SecurityToken.php
Replace internal security tokens from the old Fernet specification to the newer and more secure [Branca specification](https://branca.io).
> Replace fernet with branca

- composer.json
- www/bootstrap.inc.php
- www/config.php.dist
Enable use of the [Tracy](https://tracy.nette.org/) debugging library
> Enable Tracy debugging library

- www/cache.inc.php
In SimpleID 1.0.3, the `cache_expire` function does not really expire the cache contents a it does not descend into subdirectories.
Fixes #81
> iterate through dirs on cache cleanup

- www/core/Auth/AutoAuthEvent.php
- www/core/Auth/LoginEvent.php
- www/core/Base/IndexEvent.php
- www/core/Base/ScopeInfoCollectionEvent.php
- www/core/Models/ConsentEvent.php
- www/core/Protocols/OAuth/OAuthInitClientEvent.php
- www/core/Protocols/OAuth/OAuthInitTokenEvent.php
- www/core/Protocols/OpenID/OpenIDCheckEvent.php
- www/core/Protocols/OpenID/OpenIDResponseBuildEvent.php
- www/core/Util/Events/BaseDataCollectionEvent.php
- www/core/Util/Events/BaseEvent.php
- www/core/Util/Events/BaseStoppableEvent.php
- www/core/Util/Events/OrderedDataCollectionEvent.php
- www/core/Util/Events/UIBuildEvent.php
- www/core/Util/Forms/FormSubmitEvent.php
- www/core/Util/UI/UIBuilderInterface.php
Move most events to be subclasses of `SimpleID\Util\Events\BaseEvent`.
> Refactor events

- .github/workflows/ci.yml
- composer.json
- www/bootstrap.inc.php
PHP 7.3 is required in order to set the `samesite` parameter for cookies using [`session_set_cookie_params`].
[`session_set_cookie_params`]: https://www.php.net/manual/en/function.session-set-cookie-params.php
> Update requirements to PHP 7.3

- www/core/Protocols/Connect/ConnectModule.php
PR #102 updated the dependency on SimpleJWT to v0.8.  However the changes to the SimpleJWT API did not flow through.
> Update SimpleJWT API to v0.8

- composer.json
- www/bootstrap.inc.php
- www/config.php.dist
- www/core/Auth/AuthManager.php
- www/core/Auth/LoginEvent.php
- www/core/Auth/LogoutEvent.php
- www/core/Base/AuditEvent.php
- www/core/Base/ConsentEvent.php
- www/core/Base/MyModule.php
- www/core/Protocols/Connect/ConnectModule.php
- www/core/Protocols/OAuth/OAuthModule.php
- www/core/Protocols/OpenID/OpenIDModule.php
- www/core/Protocols/ProtocolResultEvent.php
- www/core/Protocols/ProtocolResultTrait.php
Refactor event classes to be subsclasses of `AuditEvent` to enable listeners to implement audit logging.
> Audit events

- identities/example.client.yml.dist
- tests/frontend/config.yml
- www/core/Protocols/Connect/ConnectClientRegistrationModule.php
- www/core/Protocols/CustomRedirectResponse.php
- www/core/Protocols/OAuth/OAuthClient.php
- www/core/Protocols/OAuth/OAuthModule.php
- www/core/Protocols/OAuth/Response.php
- www/html/redirect_native.html
- www/locale/en.ini
Enhance compliance against [RFC 8252], as well as user interface improvements for redirecting to custom URIs
[RFC 8252]: https://datatracker.ietf.org/doc/html/rfc8252
> Improve support for native apps

- www/core/Auth/AuthManager.php
- www/core/Auth/AuthResultInterface.php
- www/core/Auth/AuthResultTrait.php
- www/core/Auth/CertAuthSchemeModule.php
- www/core/Auth/LoginFormSubmitEvent.php
- www/core/Auth/NonInteractiveAuthEvent.php
- www/core/Auth/RememberMeAuthSchemeModule.php
This PR renames "auto authentication" to "non-interactive authentication" to better reflect what it is for.
This also cleans up some authentication features.
> Refactor authentication modules

- README.md
- RoboFile.php
- composer.json
- www/core/Store/DefaultStoreModule.php
- www/upgrade/UpgradeModule.php
Replace old YAML parsing component (spyc) with symfony/yaml
> Replace spyc with symfony/yaml

- build/build_assets.js
- package-lock.json
- package.json
Fixes https://github.com/simpleid/simpleid/security/dependabot/3
> Migrate from live-server to five-server

- phpstan.neon.dist
- www/core/Module.php
- www/core/Protocols/Connect/ConnectModule.php
- www/core/Protocols/OpenID/DiffieHellman.php
- www/core/Protocols/XRDS/XRDSDiscovery.php
> Replace pow and mod with powmod in DiffieHellman.php

- www/core/Base/MyModule.php
- www/html/my_apps.html
PR #80 introduced a number of errors in the "My Apps" page.  The PR:
* merges the `/my/apps` and `/my/apps/@cid` API calls into a single call
* fixes internationalisation issues
* fixes issues when formatting consents
> Fix issues in the "My Apps" page

- www/core/Protocols/OAuth/AccessToken.php
- www/core/Protocols/OAuth/RefreshToken.php
- www/core/Protocols/OAuth/Token.php
Adds token type to the payload of OAuth tokens, so that access and refresh tokens can be differentiates from each other.
> Add token type to OAuth tokens

- www/core/Module.php
- www/core/Protocols/Connect/ConnectClientRegistrationModule.php
- www/core/Protocols/Connect/ConnectModule.php
- www/core/Protocols/Connect/ConnectSessionModule.php
- www/core/Protocols/OAuth/OAuthModule.php
Implement [RFC 8414].  This mainly involves refactoring `ConnectModule::openid_configuration()` into `OAuthModule`.
[RFC 8414]: https://datatracker.ietf.org/doc/html/rfc8414
> Implement RFC 8414

- www/core/Protocols/OAuth/OAuthModule.php
Implement [RFC 7009].
[RFC 7009]: https://datatracker.ietf.org/doc/html/rfc7009
> Implement OAuth token revocation

- www/core/Protocols/OAuth/OAuthModule.php
- www/core/Protocols/OAuth/Token.php
Implement [RFC 7662].
[RFC 7662]: https://datatracker.ietf.org/doc/html/rfc7662
> Implement OAuth token introspection

- www/core/Store/DefaultStoreModule.php
`readlink($filename)` may return false.
> Fix static analysis error in DefaultStoreModule

- www/core/Base/MyModule.php
This PR fixes a typo (I guess) in the retrieval of the consent info weights. Otherwise, sorting by weight won't work.
> Fix weight retrieval

- .gitignore
- RoboFile.php
- apigen.neon
- composer.json
Add support for generating API documentation via [ApiGen](https://github.com/ApiGen/ApiGen)
> Add ApiGen configuration

- www/core/Util/Events/BaseDataCollectionEvent.php
- www/core/Util/Events/OrderedDataCollectionEvent.php
Refactor `OrderedDataCollectionEvent` to be a subclass of `BaseDataCollectionEvent`.
> Refactor OrderedDataCollectionEvent
